ALTER DATABASE peep CHARACTER SET utf8 COLLATE utf8_unicode_cli;

/* ONLY RUN ONCE THIS LINE DELETES THE CURRENT TABLE AND REMAKES IT!! */
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS species;
DROP TABLE IF EXISTS sighting;
DROP TABLE IF EXISTS favorite;

CREATE TABLE species(
	speciesId BINARY(16) NOT NULL,
	speciesCode VARCHAR(6) NOT NULL,
	speciesComName VARCHAR(64) NULL,
	speciesSciName VARCHAR(64) NULL,
	speciesPhoto VARCHAR(128) NULL,
	PRIMARY KEY (speciesId)
);