ALTER DATABASE peep CHARACTER SET utf8 COLLATE utf8_unicode_cli;

/* ONLY RUN ONCE THIS LINE DELETES THE CURRENT TABLE AND REMAKES IT!! */
DROP TABLE IF EXISTS species;

CREATE TABLE species(
	speciesId BINARY(16) NOT NULL,
	speciesCode VARCHAR(6) NOT NULL,
	speciesComName VARCHAR(64) NULL,
	speciesSciName VARCHAR(64) NULL,
	speciesLocX FLOAT(6, 3) NULL,
	speciesLocY FLOAT(6, 3) NULL,
	speciesDateTime DATETIME(6) NULL,
	speciesBirdPhoto VARCHAR(128) NULL,
	PRIMARY KEY (speciesId)
);